# Generated by Django 3.2.25 on 2024-05-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tentpole_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='excel_sheet',
            field=models.FileField(upload_to=''),
        ),
    ]
